[package]
name = "my-rust-python-module"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "my_rust_python_module"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.22.0"
rand = "0.8.5"
tqdm = "0.7.0"
